### ISSUE TITLE
Feature-Suggest: Alternative OpenAI URL and option for external Ollama URL

### ISSUE THREAD

**Issue by deliciousbob** [nbonamy/witsy#1]
Wow, what an amazing tool! Thx a lot for your effort! Keep on going 👍 

I would like to suggest two possible features that would enhance the possibilities of Witsy:
- Possibility to add **OpenAI URL** (for OpenAI compatible API Endpoints: http://<openai-api-endpoint>/v1/completion )
- Possibility to use **external Ollama Service** (option to specify Ollama URL: http://<ollama-server>:11434 )

Thx, best regards, Robert

**Comment by nbonamy** [comment]
On it!

**Comment by deliciousbob** [comment]
Thx for your effort 🙏🏻

**Comment by nbonamy** [comment]
Committed on trunk. Would be great if you can provide feedback before I create a new release!

**Comment by deliciousbob** [comment]
Sry for the delay, I managed to run the current version via npm and was able to test the ollama url endpoint 😊👍🏻 it was working like expected (i could not test the openai url, as my ollama openai-api did not want to work on any request - also on other tools like openwebui gave the same error)

**Comment by nbonamy** [comment]
Was able to test the OpenAI implementation successfully. Publishing a new release!

**Comment by nbonamy** [comment]
1.8.0 released

**Comment by deliciousbob** [comment]
Thank you very much, :) looking forward to test it

**Comment by nbonamy** [comment]
Check this out: https://x.com/nbonamy/status/1875970272123302318
