### ISSUE TITLE
Latex format

### ISSUE THREAD

**Issue by chllei** [nbonamy/witsy#10]
Thank you very much for developing such a useful desktop client!

While using it, I found that the current chat interface does not support LaTeX math formulas very well. I hope this can be improved. Thank you.

**Comment by chllei** [comment]
Currently, it is indeed possible to display some LaTeX formulas. Specifically, there are the following issues:

1. The font in LaTeX formulas is not uniform, which makes the equations look a bit strange.

![屏幕截图 2024-11-01 223423](https://github.com/user-attachments/assets/78e7b971-c270-4454-b811-fe7d4fa49e6f)

2. For other non-`$` LaTeX formula representations, they cannot be parsed well. See the example in the following figure.

![image](https://github.com/user-attachments/assets/9f0671bd-3192-4926-ac11-22952f1a3dd3)

**Comment by nbonamy** [comment]
What Ollama model were you using? Can you give me the equivalent prompt in English? Thanks!

**Comment by chllei** [comment]
The model is Qwen2.5-14B-Instruct. The English version is as follows:

![image](https://github.com/user-attachments/assets/d18ef70d-4cf4-4434-be95-0392fb28bb24)

It can be seen that some of the formulas have not been rendered correctly.

**Comment by nbonamy** [comment]
Ok this is what I get now (upcoming release). Looks better right?

<img width="634" alt="image" src="https://github.com/user-attachments/assets/f0920f93-42d0-48eb-bb3d-2671c596f862">

**Comment by chllei** [comment]
This is great! It looks like the new version has done a better optimization for math fonts.

Additionally, there may be some rules that need to be added regarding math delimiters. For more details, see [here](https://docs.mathjax.org/en/latest/input/tex/delimiters.html).

**Comment by nbonamy** [comment]
I am not using MathJax. Was not able to find a way to get a model to generate an equation with `$$`. Did some manual tests by hacking a response but my rendering was fine so not sure...

**Comment by nbonamy** [comment]
What this the model you used?
https://ollama.com/krith/qwen2.5-14b-instruct

**Comment by nbonamy** [comment]
Hum was able to get ChatGPT to use $$ and it seems to be working fine
<img width="736" alt="image" src="https://github.com/user-attachments/assets/3a5fd7b1-8a37-4e5e-a61a-a2583f0f3acb">
<img width="504" alt="image" src="https://github.com/user-attachments/assets/4f0d5b43-5997-4b86-ad86-a5e597a1f891">

**Comment by nbonamy** [comment]
Will close for now. Can you open a new one when you can reproduce? Thanks!

**Comment by chllei** [comment]
Thank you very much for the optimizations in the new version. I have updated the software, and it is running well.

I am currently using this [model](https://huggingface.co/bartowski/Replete-LLM-V2.5-Qwen-14b-GGUF), but actually other models can also produce similar outputs.

The current software version correctly renders LaTeX delimiters `$`, but I think it needs to add some new rules: `\(...\)` for in-line math and `\[...\]` for displayed equations, so that all mathematical formulas are rendered correctly.

**Comment by nbonamy** [comment]
Created https://github.com/nbonamy/witsy/issues/12
