### ISSUE TITLE
Experts as system prompt

### ISSUE THREAD

**Issue by chllei** [nbonamy/witsy#13]
The current "expert" feature is very creative, bringing together a multitude of excellent prompts to let the LLMs play different roles.

My view is that if we define "Expert" as part of the system prompt, would it be better? This way, the dialogue interface would be simpler and wouldn't display lengthy role definitions.

**Comment by nbonamy** [comment]
Agreed. I have been thinking about that. Just need to think of a nice way to show that the expert is "active".

**Comment by nbonamy** [comment]
Here is the current updated flow (WIP). For the moment, as the expert becomes the system prompt, you cannot disable or change the expert once a conversation is started. Not sure it is a big limitation so would like your feedback on it.

Once you have selected an expert, the icon stays blue and if you hover it, the window shows up showing you the prompt of the expert and the opportunity to disable it (if you have not started the conversation).

All the expert prompts have been reworked to remove the "my first request is" part.

Thoughts?

![SCR-20241120-hhvf](https://github.com/user-attachments/assets/c952881d-dd48-4c33-9bc9-aae01ebbb57e)
<img width="171" alt="SCR-20241120-hhxf" src="https://github.com/user-attachments/assets/f816e534-dff3-40a6-9b97-3fcf27fe4b28">
![SCR-20241120-hibl](https://github.com/user-attachments/assets/0ae88d57-1f88-45d3-aff1-23cf49eb1e6f)

**Comment by nbonamy** [comment]
Because of previous issues went for a different design. When you select an expert, an icon appears in the prompt area that you can click to get expert details.

<img width="409" alt="image" src="https://github.com/user-attachments/assets/f75026ef-118d-4db5-8845-16d48b020307">

**Comment by nbonamy** [comment]
Done in just released 1.23.0. Waiting for your feedback a few days else will close this ticket

**Comment by nbonamy** [comment]
Will close for now. Please open another issue if you find something with the redesign

**Comment by chllei** [comment]
‌‌Just tried the new version, it's quite convenient, thanks for your improvement.
