### ISSUE TITLE
BUG: Replace selection, and paste beneath does not work in Windows 11

### ISSUE THREAD

**Issue by dantosXD** [nbonamy/witsy#15]
For some reason on windows 11 Witsy does not replace the selected text when using the AI commands that are supposed to replace text or paste beneath text. It quickly flashes "Thinking" but no text is changed. It also does not matter if I select a model I know works in scratchpad, prompt anywhere, or ai commands that open in chat.

![Untitled video - Made with Clipchamp](https://github.com/user-attachments/assets/2cbc941c-2403-49d5-b801-624524551396)

**Comment by nbonamy** [comment]
Tested on Windows 10 and Windows 11 (ARM) but was not able to reproduce so far. Will look further and/or add a way to get more info of what is happening on your laptop. Two questions though:

- What is the error message displayed in the lower right corner?
- What is the 123 icon with the white border?

**Comment by dantosXD** [comment]
The error was to select text, after I correctly applied it and it did nothing. I have added a video to see what it is doing. The NUM123 icon pops up anytime I use the AI command and that is my numlock. 

https://github.com/user-attachments/assets/49f5aaad-2201-4101-bd34-191d8d6fa49f

mands.

**Comment by nbonamy** [comment]
That 123 icon is not a Witsy icon and is probably another application that is stealing the focus from Witsy and prevents it from pasting the output in the target app. No idea what this is? It only shows up when you are using Witsy?

Found that: https://answers.microsoft.com/en-us/windows/forum/all/cannot-figure-out-how-to-disable-the-caps-locknum/b396f2a2-e8a4-44a8-a0f5-61e929551db6

**Comment by dantosXD** [comment]
Yeah the only time it happens is when I use witsy I have never seen it before.

**Comment by nbonamy** [comment]
Hum for sure this is not displayed by Witsy. Witsy may do something that triggers that other software but hard to know without knowing which software it is. Is your computer a Lenovo? Have you checked on the link how to disable it?

**Comment by dantosXD** [comment]
I will try and figure it out. I would close this bug if it is just my issue!

**Comment by nbonamy** [comment]
Sorry. The new UI will allow you to copy the content and paste it yourself as a workaround.
