### ISSUE TITLE
MacOS: no can;t switch between main window and scratchpad when window hidden behind other

### ISSUE THREAD

**Issue by wilbert-vb** [nbonamy/witsy#18]
MacOS Witsy 1.23

If one window is behind the other control-tab does not switch windows.
Also the window item in the menu does not show all open windows.

**Comment by nbonamy** [comment]
Hi. On macOS, Witsy has the same keyboard shortcut than Finder to Cycle Through Windows: Cmd+`

Window menu will be populated in next version. Stay tuned!

**Comment by nbonamy** [comment]
Window menu released in 1.26. Will wait some days before closing

**Comment by wilbert-vb** [comment]
Solved
