### ISSUE TITLE
error with npm start

### ISSUE THREAD

**Issue by dlpnet** [nbonamy/witsy#2]
Looks pretty interesting (as was cam2pc :) )

Got some errors just trying to run it (node 22 installed):

npm start

> witsy@1.7.3 start
> cross-env DEBUG=1 electron-forge start

✔ Checking your system
❯ Locating application
✔ Locating application
❯ Loading configuration
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
✔ Loading configuration
❯ Preparing native dependencies
✔ Preparing native dependencies
❯ Running generateAssets hook
✔ Running generateAssets hook
❯ [plugin-vite] Launching dev servers for renderer process code
failed to load config from witsy/vite.renderer.config.ts
✖ [plugin-vite] Launching dev servers for renderer process code [FAILED: No "exports" main defined in witsy/node_modules/estree-walker/package.json]

An unhandled rejection has occurred inside Forge:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in witsy/node_modules/estree-walker/package.json

**Comment by dlpnet** [comment]
found the issue, I had to clean the npm cache and try again:
npm cache clean
rm -rf node_modules
rm package-lock.json
npm install
npm start

**Comment by nbonamy** [comment]
Glad you were able to fix it! How do you know cam2pc? How do you know it's me? 😀
