### ISSUE TITLE
JS error occurred when edit shortcut

### ISSUE THREAD

**Issue by Joker-Jelly** [nbonamy/witsy#24]
<img width="521" alt="image" src="https://github.com/user-attachments/assets/dc0d3305-7bd0-4cf6-89d9-ea1f38b8dfd4" />
I meet a JS error when try to edit the shortcut, and sadly if I closed this then it will be show up again. 
I guess the reason might because I change the shortcut to some unknown key.

**Comment by nbonamy** [comment]
Never tested with a numeric keypad but fixed now. Will be available in 1.27.1 in a few!
