### ISSUE TITLE
together.ai - Chat model dropdown remains empty

### ISSUE THREAD

**Issue by Poldi1977** [nbonamy/witsy#27]
Hello

I'm using the provider together.ai, which offers an OpenAI-compatible API. I have correctly filled in the "API key" and "API Base URL" (https://api.together.xyz/v1) and clicked the "Refresh" button. Nevertheless, the "Chat model" remains empty.

Has the application been tested with together.ai?

Best regards
Poldi

**Comment by nbonamy** [comment]
Hey just checked and it seems that even though together.ai says they support OpenAI API, they have slight differences especially on how the model list is supported. Was able to handle that but what's more problematic is that Together.ai does not support plugins for all models and did not find a way to know which ones are supported which ones are not.

Not sure how to handle that just yet so will need more time.

**Comment by nbonamy** [comment]
Available in 1.28.0. Waiting for feedback for a few days

**Comment by Poldi1977** [comment]
Yes, actually, it works now! Thanks a million for the quick troubleshooting!

**Comment by nbonamy** [comment]
Check this out: https://x.com/nbonamy/status/1875970272123302318
