### ISSUE TITLE
AI Commands and Read Aloud do not work

### ISSUE THREAD

**Issue by Poldi1977** [nbonamy/witsy#28]
Hello

I get the following error message after selecting text in any application and pressing the shortcut for `AI Commands`. The same happens with `Read Aloud`.
![grafik](https://github.com/user-attachments/assets/cad9c5b7-0161-4c3b-8e89-29467d42ff3b)

OS: Ubuntu 24.04.1 LTS
Desktop: Xfce4
Witsy Version: 1.28

The log file contains an error message:
> tim@nb-dell:~$ witsy 
> 23:46:33.320 › Checking for updates at https://update.electronjs.org/nbonamy/witsy/linux-x64/1.28.0
> 23:46:33.323 › Nestor initialized
> 23:46:33.386 › Unregistering shortcuts
> 23:46:33.388 › Registering shortcuts
> 23:46:33.388 › Registering shortcut { key: 'C', ctrl: false, alt: false, shift: false, meta: true } Command+C
> 23:46:33.390 › Registering shortcut { key: 'Space', alt: true, ctrl: true } Alt+Control+Space
> 23:46:33.391 › Registering shortcut { key: 'A', shift: false, meta: true, alt: false, ctrl: false } Command+A
> 23:46:33.392 › Registering shortcut { key: 'Space', alt: true, shift: false, ctrl: true, meta: true } Alt+Control+Command+Space
> 23:46:33.392 › Registering shortcut { key: 'Space', shift: true, ctrl: true, alt: true } Alt+Control+Shift+Space
> 23:46:33.393 › Registering shortcut { key: 'S', meta: true, alt: false, shift: false, ctrl: false } Command+S
> 23:46:33.439 › Loading file: /usr/lib/witsy/resources/app.asar/.vite/renderer/main_window/index.html
> 23:46:33.439 › With options: /prompt {}
> 23:47:16.813 › Loading file: /usr/lib/witsy/resources/app.asar/.vite/renderer/main_window/index.html
> 23:47:16.813 › With options:  {}
> 23:47:17.132 › Processing query params {} file:///usr/lib/witsy/resources/app.asar/.vite/renderer/main_window/assets/index-CXSsO1_n.js:2712
> 23:47:31.715 › Error: Method not implemented.
>     at P0.getForemostAppPath (/usr/lib/witsy/resources/app.asar/.vite/build/main.js:312:120)
>     at si.getForemostAppPath (/usr/lib/witsy/resources/app.asar/.vite/build/main.js:312:3446)
>     at AsyncFunction.<anonymous> (/usr/lib/witsy/resources/app.asar/.vite/build/main.js:312:5778)
> 23:47:31.728 › No text selected

Best regards
Poldi

**Comment by nbonamy** [comment]
Hopefully things should look better on Linux with just released 1.29.0. Please keep this issue opened only related to the text grabbing issue (No text selected), otherwise open a new issue. Thanks.

**Comment by Poldi1977** [comment]
It looks fantastic under Linux. Thank you very much!
