### ISSUE TITLE
The question about global prompt.

### ISSUE THREAD

**Issue by 2214372851** [nbonamy/witsy#29]
![image](https://github.com/user-attachments/assets/7b3034c9-af9f-456b-aad0-73b72ddf8d65)
Hello, my understanding is that the last configuration is for the global prompt, but I've noticed that the model doesn't seem to follow it when I use it. Am I misunderstanding something?

**Comment by nbonamy** [comment]
Yes that's what it is and it should work. Can you please provide the instructions you are trying to use?

<img width="688" alt="image" src="https://github.com/user-attachments/assets/df2f0c9d-404a-42b1-97a9-45ef256afa4a" />

**Comment by 2214372851** [comment]
I've found that it might be related to Gemini; the instructions are not being completely followed, and it's not a software issue.
