### ISSUE TITLE
Feature-Suggest: RAG and TTS

### ISSUE THREAD

**Issue by snakeying** [nbonamy/witsy#3]
This desktop app looks very promising, keep up the great work!

Besides the Feature-Suggest: Alternative OpenAI URL and the option for an external Ollama URL @deliciousbob, I recommend adding RAG and TTS functionalities.

1. For RAG, I suggest using the all-MiniLM-L6-v2 model (https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2). It's very compact, occupying less than 50MB even in fp16. Although its dimensionality (384 vs. 1536) is lower compared to OpenAI's text-embedding-ada-002, the all-MiniLM-L6-v2 model performs well in practical applications and is free to use. Of course, I also recommend keeping the OpenAI embedding option available for user preference.

2. For TTS, I suggest using edge-tts (https://migushthe2nd.github.io/MsEdgeTTS/index.html). It is also free and performs excellently in multilingual scenarios.

**Comment by nbonamy** [comment]
Was thinking about RAG but still unclear how this would work. I am thinking local to a specific conversation but not necessarily intuitive to remember that this conversation is "RAG enabled" for the user... 

Have you put any thoughts into it?

Thanks!

**Comment by nbonamy** [comment]
Read aloud was added to Witsy!

**Comment by nbonamy** [comment]
RAG has been added to trunk. You can test it. For the moment it only supports OpenAI embeddings. Check it out if you are still interested. Will polish before releasing.

- Create a document repository by clicking on database icon left of prompt
- Add documents then close window
- Click on database again and "connect" your chat to the document repository

**Comment by nbonamy** [comment]
Added all-MiniLM-L6-v2 (and other models) support via https://github.com/Anush008/fastembed-js

**Comment by nbonamy** [comment]
1.12 released with RAG aka Document Repository. Check README.
Added Ollama embedding on top of OpenAI ones

**Comment by nbonamy** [comment]
Check https://x.com/nbonamy/status/1833133569436176583 for a demo

**Comment by nbonamy** [comment]
1.12.4 should be pretty mature for RAG. Closing this issue. Please open a bug report if you find something!
