### ISSUE TITLE
Cannot set context size

### ISSUE THREAD

**Issue by davidcampos** [nbonamy/witsy#30]
It would be great to have settings for configuring the model parameters, such as the context size.

**Comment by nbonamy** [comment]
Hi. As far as I understand, context size is a characteristic of the model and cannot be configured.

In Witsy, you can configure the "Conversation Length" which will translate to how much context you are sending to the model.

<img width="664" alt="image" src="https://github.com/user-attachments/assets/1c7030c8-2ca4-4ba1-bda9-c1424cc8ecbb" />

Is it what you were looking for or something else?

**Comment by davidcampos** [comment]
FYI: solved it by setting the context size parameter on the ollama model 😄
