### ISSUE TITLE
Connecting to Ollama

### ISSUE THREAD

**Issue by punk1234567** [nbonamy/witsy#31]
Hi Friend,

Great tool. Thanks.

I am trying to connect to Ollama running on a Cloud server. Is this even possible. If yes, kindly let me know the process. Thanks.

Sam

**Comment by nbonamy** [comment]
Hi! Glad you like it 😀 Spread the word!

You can define a Base URL for Ollama in the settings. That should allow you to connect to any instance!

<img width="668" alt="image" src="https://github.com/user-attachments/assets/fdf59b2f-2a01-4dfa-a0d4-68ff9720f612" />

**Comment by punk1234567** [comment]
Thanks for the quick response. As i mentioned i am providing the remote cloud address of the ollama server in the API Base URL. I am using Llama3.1 8B. Whatever question I ask, the response that i get is something like this "The text you provided is a dump of the HTML code of a Wikipedia page, and it's not suitable for analysis or summarization.

However, I can help you extract some information from this dump. Here are a few things I found:"

Can you help resolve this. thanks.

**Comment by nbonamy** [comment]
Hi. Glad you were able to connect to our ollama server. As for the response you get, it is what the model outputs. Maybe you should try with a bigger model (70B vs 8B).
