### ISSUE TITLE
Ollama with API Key

### ISSUE THREAD

**Issue by davidcampos** [nbonamy/witsy#32]
Is it also possible to set up Ollama integration using an API key?
Thanks for your help!

**Comment by nbonamy** [comment]
In which context would you need an API key for Ollama? Their SDK does not have support for an API key so not sure...

https://github.com/ollama/ollama-js

**Comment by davidcampos** [comment]
Added an API Key with a Traefik Middleware. Just to make sure that external access is not open.

**Comment by nbonamy** [comment]
Sorry but it seems like a very specific request considering the Ollama SDK does not even support API keys. Will close for now.
