### ISSUE TITLE
Feature requests: exporting command, auto-minimize, custom command in Prompt Anywhere and Chat, and plugin documentation

### ISSUE THREAD

**Issue by irosyadi** [nbonamy/witsy#4]
Hi, I am a big fan of Witsy, and it has become my daily tool of choice. Previously, I used a custom Autohotkey script for my tasks, but Witsy replaced it due to its numerous features. The "AI Command" feature is the one I use the most. However, I have some feature requests: 

1. An option to export/import "AI Command". I have several custom "AI Command" settings that I want to back up and export to another computer without rewriting them. 
2. An option to automatically minimize Witsy when it starts with Windows login. 
3. The ability to use Custom "AI Command" with the "Prompt Anywhere" command. This would enable faster execution of frequently used prompts. For example, I often create dummy JSON files. I could select the custom command for JSON creation and then just prompt the content in "Prompt Anywhere". 
4. Also, the ability to customize prompts (from https://github.com/f/awesome-chatgpt-prompts) in the main chat window since I have some custom prompts that better meet my requirements than the provided ones.   
5. I am not sure how to get the plugins to work. I tried all of them with no success. I searched for documentation but it seems to be unavailable. 
6. Witsy version and update notification. I don't know the Witsy version I am using or whether it needs to be updated to a new version.

Witsy has been a fantastic tool for me and I appreciate you making it so great. 
Thank you very much.

**Comment by nbonamy** [comment]
Hi @irosyadi and thanks for the positive feedback!

1. That is easy. Meanwhile you can look in the application configuration folder (https://www.electronjs.org/docs/latest/api/app#appgetpathname) and copy the commands.json file

2. Tried to do that with Electron but it seems MacOS is preventing to do that in latest versions. Will take another look.

3. OK. Will think about that.

4. Same

5. Plugins should work automatically as long as you have configured them. Ask GPT to summarize a URL and it should fetch the content automatically for instance

6. Is obvious on the Mac version (About and Check for Update are in the main menu). Will run Witsy on Windows and check!

**Comment by irosyadi** [comment]
Thanks!  
1. I found the command.json file in %APPDATA%\Roaming\Witsy.  
5. Oh okay, I understand how the plugins work by adjusting the prompt.  
6. Yes, I use Witsy on Windows and couldn't find any About or Update Check menus.

**Comment by nbonamy** [comment]
Just released 1.8.2:

- About Witsy in Windows tray icon menu. Check for updates need more work
- Import/Export commands

**Comment by nbonamy** [comment]
Just released 1.10.0:

- Customized Prompts renamed to Experts
- Experts are now editable / exportable / importable
- Experts are now available in Prompt Anywhere

**Comment by irosyadi** [comment]
Wow, thank you very much. They pretty much meet my workflow when using Witsy.

**Comment by nbonamy** [comment]
Closing this issue and opening two of the remaining things:

- Automatically minimize on startup
- Auto-update for Windows

**Comment by senovr** [comment]
@nbonamy , follow-up question on this already-closed issue.

Can you please confirm, that when we are speaking about search with tavily api key, you have to provide url where to search?

 So, it is not the same experience like in perplexity - where you just type a question and it search first, and summarizes it with LLM?

**Comment by senovr** [comment]
Hmm, just tried it with ollama-hosted mistral-nemo, and can not make it to use internet search... my test case was simple - who is president-elect on 2024 elections in US, and mistral keep answering (and hallucinating from time to time) i dont know, i can not look into future. This happens even when I mention - use internet search for answering this question.

**Comment by nbonamy** [comment]
Ollama is not supported because of https://github.com/ollama/ollama-js/issues/123.

**Comment by senovr** [comment]
ok, thanks for clarification. Will follow this issue to track progress.

**Comment by nbonamy** [comment]
Available in 1.26. Probably some tweaking...

**Comment by senovr** [comment]
Just tried - worked, sometimes weird, sometimes great.
As an example, during my simple test described above - sometimes it simply
outputs the name, sometimes -gives tons of text about the election process,
etc.
But it looks good as a starting point

**Comment by nbonamy** [comment]
Created https://github.com/nbonamy/witsy/issues/20 to discuss this further
